export { default as About } from "./about/About"
export { default as Contact } from "./contact/Contact"
export { default as Events } from "./events/Events"
export { default as Footer } from "./footer/Footer"
export { default as Header } from "./header/Header"
export { default as Donate } from "./donate/Donate"
