export { default as About } from "./about/About"
export { default as Contacts } from "./contacts/Contacts"
export { default as Events } from "./events/Events"
export { default as Footer } from "./footer/Footer"
export { default as Header } from "./header/Header"
export { default as Donate } from "./donate/Donate"
export { default as Student } from "./student/Student"
export { default as Admin } from "./admin/Admin"
export { default as Teacher } from "./teacher/Teacher"
export { default as Church } from "./church/Church"

